name: birdseye
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cairo
  - cairosvg
  - jedi
  - jupyterlab
  - line_profiler
  - noise
  # I installed this via scoop
  #  - openjdk=11.0.8
  - pip
  - pip:
      - py5
